package android.alliance.exceptions;

public enum AllianceExceptionType {

	PREVIEW_EXCEPTION,
	TAKE_PHOTO_EXCEPTION,
	ON_PICTURE_TAKEN_EXCEPTION,
	ORIENTATION_CHANGED_EXCEPTION,
	CAMERA_FAILED_TO_OPEN_EXCEPTION,
	FLASHLIGHT_EXCEPTION,
	ZOOM_EXCEPTION,
	CAMERA_NOT_STARTED_EXCEPTION,
	OTHER;
	
}
